// School data for Bangalore
// Last updated: March 2026 — Fee data verified March 2026
// Fees shown as 2026-27 estimates (~10% over 2025-26 verified data)
// To add a school: copy any object below, change the values, add to the array
// To add a new corridor: add a new entry to CORRIDORS, then add schools with that corridor's id in the 'cor' field

const CORRIDORS = [
  {
    "id": "east",
    "name": "East Bangalore",
    "sub": "Marathahalli → Kasturinagar → ORR → Whitefield → Hoskote",
    "count": 40,
    "active": true
  },
  {
    "id": "north",
    "name": "North Bangalore",
    "sub": "Hebbal → Yelahanka → Devanahalli → Airport Road",
    "count": 0,
    "active": false
  },
  {
    "id": "south",
    "name": "South Bangalore",
    "sub": "Bannerghatta → JP Nagar → Electronic City",
    "count": 0,
    "active": false
  },
  {
    "id": "sarjapur",
    "name": "Sarjapur Road",
    "sub": "HSR Layout → Bellandur → Haralur → Sarjapur → Dommasandra",
    "count": 0,
    "active": true
  },
  {
    "id": "west",
    "name": "West Bangalore",
    "sub": "Rajajinagar → Malleshwaram → Yeshwanthpur",
    "count": 0,
    "active": false
  },
  {
    "id": "central",
    "name": "Central Bangalore",
    "sub": "MG Road → Indiranagar → Koramangala → Jayanagar",
    "count": 0,
    "active": false
  }
];

const SCHOOLS = [
{"n":"Chrysalis High","l":"Whitefield/Varthur","z":"Whitefield","cor":"east","f":1.6,"fl":"~₹1.55-1.70L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"11:1","ri":11,"y":2010,"sz":"Small","s":{"af":66,"co":88,"st":68,"ra":95,"op":85,"ac":70,"di":75,"inf":60,"al":35,"ad":82},"g":1,"ap":"High","t":["11:1 ratio","Understanding-based","Small batches"],"tc":["g","g","b"],"ph":"Understanding each child individually; sports & performing arts integral; small batches enable deep engagement. Philosophy centers on knowing every student personally.","adm":"Open admissions with interaction session. No entrance exam for Class 1. Moderate demand — not as oversubscribed as NPS/DPS. Klay has no priority but no disadvantage.","bf":"Families wanting personal attention + AI-age-ready conceptual learning at budget price","pros":["Best student-teacher ratio in corridor","Understanding-based not rote","Within ₹1.5L budget","Sports & performing arts strong"],"cons":["Smaller campus","Limited alumni network","Less brand recognition than NPS/DPS","STEM infrastructure still developing"],"url":"https://chrysalishigh.com","ph2":"+91-80-41550750"},
{"n":"VIBGYOR Rise Panathur","l":"Panathur/Kadubeesanahalli","z":"Panathur","cor":"east","f":1.75,"fl":"~₹1.63-1.89L/yr (2026-27 est.)","b":"CBSE+CISCE","a":"Conceptual","r":"10:1","ri":10,"y":2017,"sz":"Medium","s":{"af":60,"co":82,"st":75,"ra":98,"op":78,"ac":72,"di":78,"inf":80,"al":45,"ad":75},"g":1,"ap":"Med-High","t":["10:1 ratio!","Gardner MI","Dual board","Kolb experiential"],"tc":["g","p","b","g"],"ph":"Uses Gardner's Multiple Intelligences + Kolb's experiential learning theory. 10:1 ratio is the best in the entire corridor. AC classrooms, skating rink, basketball court, cricket area. Offers both CBSE and CISCE — you can choose board at enrollment.","adm":"Growing school — newer campus means more seats than established schools. Interaction-based admission. Both CBSE and ICSE options available at enrollment.","bf":"Families wanting the absolute best ratio + modern evidence-based pedagogy + dual board flexibility","pros":["10:1 ratio — best in corridor","Evidence-based pedagogy (Gardner + Kolb)","Dual board CBSE + ICSE choice","VIBGYOR group backing","Modern AC campus"],"cons":["Newer school (est. 2017) — less track record","Fees at upper edge of ₹1.5L budget","Currently only up to middle school — will need to extend","Panathur location may be far from Kasturinagar"],"url":"https://www.vibgyorrise.com/school/bengaluru/cbse/panathur","ph2":"+91-6003000700"},
{"n":"TCIS Whitefield","l":"Whitefield","z":"Whitefield","cor":"east","f":1.65,"fl":"~₹1.52-1.85L/yr (2026-27 est.)","b":"CBSE+IB","a":"Conceptual","r":"20:1","ri":20,"y":2015,"sz":"Medium","s":{"af":64,"co":92,"st":82,"ra":72,"op":90,"ac":78,"di":78,"inf":80,"al":55,"ad":78},"g":1,"ap":"High","t":["British Council","PASCH school","Inquiry-driven","#2 Emerging TOI"],"tc":["p","p","g","g"],"ph":"Inquiry-driven CBSE+IB blend. British Council International Dimension in Schools Award (2024-25). PASCH school with German language. Ranked #2 Emerging School in Bangalore by Times of India 2024. Fosters creativity, confidence, and global readiness.","adm":"Interaction-based admission. Progressive school attracts specific parent profile — those who value international orientation. Moderate competition. German language offering is unique.","bf":"Globally-minded families wanting progressive international pedagogy at CBSE price point","pros":["Highest conceptual learning score in corridor","British Council + PASCH credentials","CBSE + IB blend — rare at this price","German language unique offering","Ranked by Times of India"],"cons":["Less competitive exam focus may concern some parents at Class 10-12 stage","Fees at upper edge","Newer school — smaller alumni base","20:1 ratio is good but not exceptional"],"url":"https://www.tcis.ac.in","ph2":"+91-80-42064444"},
{"n":"EuroSchool Whitefield","l":"Whitefield/Hoodi","z":"Whitefield","cor":"east","f":1.75,"fl":"~₹1.35-2.17L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"19:1","ri":19,"y":2010,"sz":"Large","s":{"af":60,"co":78,"st":75,"ra":78,"op":70,"ac":72,"di":75,"inf":78,"al":50,"ad":80},"g":0,"ap":"High","t":["LRPAX method","19:1 ratio","Chain reliable"],"tc":["b","g","b"],"ph":"LRPAX methodology (Learn-Reinforce-Practice-Apply-Experience) designed to reduce rote learning. BEEP teacher upskilling program. ASPIRE program with global experts. Serves families from Whitefield, Kadugodi, Hoodi, Marathahalli, Kundalahalli, Brookefield, Mahadevapura.","adm":"Chain school — structured admission with multiple seats. Online enquiry → counselling session → interaction → documents → fees. Moderate competition. No feeder advantage from Klay.","bf":"Families wanting reliable, predictable quality with conceptual approach and chain consistency","pros":["LRPAX method is genuinely anti-rote","Teacher upskilling built into chain model","19:1 ratio — good for chain school","Wide coverage across East Bangalore","Predictable quality — you know what you get"],"cons":["Chain schools can feel corporate","Less unique personality than standalone schools","STEM good but not outstanding","EuroKids preschool gets some priority — Klay doesn't"],"url":"https://www.euroschoolindia.com/best-schools-in-bangalore/cbse-whitefield/","ph2":"+91-80-47097709"},
{"n":"Presidency School East","l":"Kasturinagar","z":"Kasturinagar","cor":"east","f":1.74,"fl":"~₹1.74L/yr (2026-27 est.)","b":"CBSE","a":"Mixed-Conceptual","r":"25:1","ri":25,"y":2006,"sz":"Large","s":{"af":60,"co":72,"st":65,"ra":62,"op":68,"ac":80,"di":78,"inf":75,"al":65,"ad":85},"g":1,"ap":"High","t":["41yr Presidency brand","YOUR area","Affordable","Board results strong"],"tc":["p","g","g","g"],"ph":"Presidency Group of Institutions — 41+ years of legacy. Formative + summative assessment approach. Holistic campus in Kasturinagar. Brilliant board results across curricula and levels. Affordable fee structure by design. Known for competitive exam prep alongside holistic development.","adm":"Admissions OPEN for 2026-27. Registration via website → placement test (English, Math, EVS for Class 1) → interview. First-come basis. Kasturinagar location means less oversubscribed than Whitefield schools. High admission probability for your profile.","bf":"Families in Kasturinagar/east corridor wanting proven brand + affordability + strong academic results","pros":["41-year Presidency Group legacy","Right in Kasturinagar — minimal commute","Very affordable at ₹1-1.2L","Strong board results track record","Admissions currently open"],"cons":["25:1 ratio — larger than boutique schools","More mixed than purely conceptual approach","STEM infrastructure developing, not leading-edge","Can lean toward traditional methods depending on teacher"],"url":"https://presidencyschooleast.org","ph2":"+91-9620812270"},
{"n":"Glentree Academy","l":"Whitefield","z":"Whitefield","cor":"east","f":1.5,"fl":"~₹1.39-1.65L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"16:1","ri":16,"y":2003,"sz":"Medium","s":{"af":70,"co":80,"st":65,"ra":80,"op":82,"ac":68,"di":72,"inf":65,"al":30,"ad":85},"g":1,"ap":"High","t":["Curiosity-driven","Great value","Community focus"],"tc":["g","g","b"],"ph":"Cultivates passion-driven approach to learning. Curriculum designed to harness natural curiosity and foster community-building and discipline through interactions with environment. 53.8% of parents rate school as 'generally good' in independent surveys.","adm":"Growing school — usually has seats available. Standard registration + interaction. Not heavily oversubscribed. Good admission odds for most profiles.","bf":"Families wanting open, non-pressured, curiosity-driven environment at excellent value","pros":["Philosophy genuinely curiosity-driven","Excellent value for money","Not a pressure-cooker","Community-building emphasis","Good admission availability"],"cons":["Still building reputation","STEM infrastructure developing","Smaller brand than NPS/DPS/Presidency","Limited alumni network — school is 14 years old"],"url":"https://www.glentreeacademy.com","ph2":""},
{"n":"Orchids International","l":"CV Raman Nagar","z":"CV Raman Nagar","cor":"east","f":1.1,"fl":"~₹1.10L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"15:1","ri":15,"y":2013,"sz":"Large","s":{"af":83,"co":72,"st":75,"ra":80,"op":65,"ac":72,"di":70,"inf":72,"al":45,"ad":88},"g":0,"ap":"High","t":["15:1 ratio","STEAM focus","75K+ alumni","Central location"],"tc":["g","b","b","g"],"ph":"Learning-by-doing philosophy. STEAM focus with digital classrooms standard across all branches. 75,000+ students educated chain-wide. CV Raman Nagar branch is central to Marathahalli-Whitefield corridor. Free remedial classes available. Prepares for JEE/NEET alongside holistic development.","adm":"Large chain — ample seats across multiple branches. Online application. Very accessible admission process. High probability of admission. Multiple Bangalore branches give flexibility.","bf":"Families wanting proven chain with good ratio near Marathahalli — safe reliable choice","pros":["15:1 ratio — strong for a chain","STEAM focus with digital classrooms","Multiple locations — flexibility","Very high admission probability","Free remedial classes"],"cons":["Franchise model — quality can vary by branch","Can feel production-line","Less unique personality","Standardized approach may not suit all children"],"url":"https://www.orchidsinternationalschool.com","ph2":"+91-8049687977"},
{"n":"Ekya School (CMR Group)","l":"Whitefield area","z":"Whitefield","cor":"east","f":1.72,"fl":"~₹1.56-1.87L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"20:1","ri":20,"y":2016,"sz":"Medium","s":{"af":61,"co":85,"st":72,"ra":75,"op":85,"ac":74,"di":72,"inf":72,"al":45,"ad":65},"g":1,"ap":"Med","t":["Entrance test required","CMR 35yr legacy","Progressive","Selective"],"tc":["a","p","g","a"],"ph":"CMR Group 35-year legacy in education. Students must pass Ekya SET (Student Entrance Test) — this is a selective school. Creates a stimulating and caring learning community. Progressive academic program. 'Ekya' means unity — school unites academic rigor with creative exploration.","adm":"SELECTIVE — requires Ekya SET entrance test. This reduces admission probability compared to open-admission schools. Test covers age-appropriate concepts. ~60-70% of applicants who take the test get offers. Not guaranteed even with a strong child.","bf":"Families comfortable with entrance selection who want progressive education with serious academic backing","pros":["Selective = higher peer quality","CMR Group 35-year education legacy","Genuinely progressive pedagogy","Stimulating environment by design","Good STEM investment"],"cons":["Entrance test — no guaranteed admission","Less accessible than open-admission schools","Relatively newer as Ekya brand","Less brand cachet than NPS/DPS despite strong quality"],"url":"https://www.ekyaschools.com","ph2":""},
{"n":"Jain Heritage School","l":"Whitefield","z":"Whitefield","cor":"east","f":1.85,"fl":"~₹1.9L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"22:1","ri":22,"y":2008,"sz":"Medium","s":{"af":57,"co":82,"st":70,"ra":70,"op":78,"ac":72,"di":70,"inf":72,"al":55,"ad":78},"g":1,"ap":"Med-High","t":["Finnish pedagogy","Jain Group","Minimal homework","Play-based"],"tc":["g","p","g","g"],"ph":"Jain Group of Institutions backing. Finnish Pedagogy approach — Finland consistently ranks #1 globally in education outcomes. Play-based learning, minimal homework, deep trust in teachers. Sets highest standards for academic achievement combined with ethical awareness and sportsmanship.","adm":"Jain Group backing means established, structured admission process. Interaction-based assessment. Moderate competition. Finnish pedagogy attracts progressive parents specifically.","bf":"Families drawn to Nordic education philosophy — play-based, minimal homework, trust-centered — at Indian price","pros":["Finnish pedagogy — globally #1 education model","Minimal homework philosophy","Jain Group institutional backing","Ethical awareness emphasis","Play-based learning in early years"],"cons":["Finnish model may feel unconventional to traditional parents","Less competitive exam focus","Fees at upper edge of budget","Not as well-known as NPS/DPS brand"],"url":"https://www.jainheritiageschool.com","ph2":""},
{"n":"Whitefield Global School","l":"Whitefield","z":"Whitefield","cor":"east","f":1.6,"fl":"~₹1.51-1.73L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"28:1","ri":28,"y":2008,"sz":"Medium","s":{"af":66,"co":62,"st":55,"ra":58,"op":65,"ac":62,"di":68,"inf":65,"al":25,"ad":90},"g":1,"ap":"High","t":["Very affordable","2.5 acres","Since 2008"],"tc":["g","b","b"],"ph":"Established 2008 on picturesque 2.5 acres, free from noise pollution. Fine blend of modern techniques with time-tested methods. Value-based education. Good basics at very affordable price point.","adm":"Usually has seats available. Standard registration. Not heavily oversubscribed. Very accessible admission.","bf":"Budget-conscious families wanting decent solid basics in Whitefield — frees cash for emergency fund","pros":["Very affordable — well under budget","2.5-acre noise-free campus","18 years established","Saves money for emergency fund or external STEM classes"],"cons":["28:1 ratio — larger classes","Traditional CBSE approach at core","Limited STEM investment","Smaller brand — won't impress on CV"],"url":"","ph2":""},
{"n":"Vydehi School of Excellence","l":"Whitefield","z":"Whitefield","cor":"east","f":1.39,"fl":"~₹1.4L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"23:1","ri":23,"y":2010,"sz":"Medium","s":{"af":74,"co":65,"st":58,"ra":68,"op":68,"ac":65,"di":72,"inf":68,"al":40,"ad":85},"g":0,"ap":"High","t":["Vydehi group backing","Inclusive","Affordable"],"tc":["b","g","g"],"ph":"Part of Vydehi group (major institutional backing = long-term stability). Positive, inclusive learning environment where every child has opportunity to achieve full potential. Improving year on year.","adm":"Institutional backing means stable operations and structured admissions. Standard registration + interaction. Usually has availability.","bf":"Families wanting affordable school with strong institutional stability and inclusive environment","pros":["Vydehi group stability — not going anywhere","Very affordable","Inclusive positive environment","Improving yearly"],"cons":["Not cutting-edge on STEM","More conventional CBSE framework","Execution varies by individual teacher","Not a standout on any single parameter"],"url":"","ph2":""},
{"n":"DPS Bangalore East","l":"Sulikunte/Dommasandra","z":"Sulikunte","cor":"east","f":1.65,"fl":"~₹1.6L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"28:1","ri":28,"y":2011,"sz":"Large","s":{"af":64,"co":75,"st":78,"ra":58,"op":65,"ac":80,"di":78,"inf":80,"al":82,"ad":72},"g":0,"ap":"Med-High","t":["DPS Society brand","National alumni","Experiential"],"tc":["p","p","g"],"ph":"Part of DPS Society — one of India's most powerful school networks. Experiential learning emphasis. Critical thinking and collaboration focus. Modern facilities. National alumni network gives lifelong connections.","adm":"DPS brand = consistently high demand. Registration → age-appropriate assessment → parent interview. Moderate-high competition. Location note: Sulikunte/Dommasandra is southeast — check commute time from your specific area.","bf":"Families wanting national-level brand + experiential learning + powerful alumni network (check commute)","pros":["DPS Society national network","Strong academic results","Experiential learning emphasis","Powerful alumni network across India","Good STEM investment"],"cons":["28:1 ratio — large sections","Sulikunte location — may be far from Marathahalli/Kasturinagar","DPS brand means competitive admission","Can be pressure-oriented in higher classes"],"url":"https://www.dpsbangaloreeast.com","ph2":""},
{"n":"Ryan International","l":"Kundalahalli/Brookefield","z":"Kundalahalli","cor":"east","f":1.38,"fl":"~₹1.10-1.65L/yr (2026-27 est.)","b":"ICSE","a":"Mixed","r":"30:1","ri":30,"y":1999,"sz":"Very Large","s":{"af":74,"co":62,"st":60,"ra":50,"op":55,"ac":72,"di":72,"inf":70,"al":60,"ad":85},"g":0,"ap":"High","t":["ICSE board","25yr legacy","3000+ students"],"tc":["b","p","b"],"ph":"Ryan International Group — one of India's largest school chains. ICSE curriculum with focus on core values for personal and interpersonal growth. 3000+ students. NASA educational workshops, media programs, social service camps. 25-year track record in Kundalahalli.","adm":"Large school with ample seats. Standard ICSE admission process. High probability of admission. Multiple Ryan branches in Bangalore give flexibility.","bf":"Families wanting established ICSE school in Kundalahalli-Brookefield with maximum seat availability","pros":["25-year track record","ICSE board — stronger in language/comprehension","Very high admission probability","Affordable for ICSE","NASA workshops unique"],"cons":["30:1 ratio — one of the largest in corridor","Can feel like a factory","ICSE may limit competitive exam prep","Chain model — less personal"],"url":"https://www.ryaninternational.org","ph2":""},
{"n":"NPS Marathahalli","l":"Balagere Road","z":"Marathahalli","cor":"east","f":1.94,"fl":"~₹1.9L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"25:1","ri":25,"y":2023,"sz":"Large","s":{"af":54,"co":68,"st":78,"ra":62,"op":50,"ac":82,"di":80,"inf":85,"al":80,"ad":70},"g":1,"ap":"Med-High","t":["9 acres!","NPS brand","NEW campus","Still accepting 26-27"],"tc":["b","p","g","g"],"ph":"NPS Super 4 newest campus — 9 acres on Balagere Road (biggest campus in NPS group). Same management and pedagogy as NPS Whitefield. Lexile Framework for personalized reading. Interactive panels in all classrooms. 240+ CCTV cameras. NPS Connect parent portal.","adm":"STILL ACCEPTING registrations for 2026-27 (unlike NPS Whitefield which is closed). NPS brand = competitive but new campus = more seats available than established branches. Online registration → Student Proficiency Assessment (SPA).","bf":"Families wanting NPS brand quality on a newer, less-crowded, spacious campus — best NPS option for 2026-27","pros":["NPS brand and pedagogy","9-acre campus — largest in NPS group","Still accepting 2026-27 admissions","Same quality as NPS Whitefield but less crowded","Near Marathahalli, Varthur, Panathur"],"cons":["Over ₹1.5L budget","New school — culture still establishing","NPS system can be rigid and pressure-heavy","25:1 ratio — standard NPS"],"url":"https://npsmarathahalli.com","ph2":""},
{"n":"NPS Whitefield","l":"Whitefield central","z":"Whitefield","cor":"east","f":1.87,"fl":"~₹1.87L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"28:1","ri":28,"y":2010,"sz":"Large","s":{"af":56,"co":65,"st":80,"ra":58,"op":45,"ac":92,"di":82,"inf":88,"al":90,"ad":35},"g":0,"ap":"Low","t":["98.8% top CBSE score","NPS brand","⚠ CLOSED for 26-27"],"tc":["g","p","r"],"ph":"NPS Super 4; achieved highest CBSE Grade 12 score of 98.8% in Bangalore Sahodaya schools. Grade 10 cohort averaged 92%. 56 medals at SASMO (Asia's most competitive math Olympiad). 4-acre campus. Lexile Framework. NPS Connect parent portal.","adm":"⚠ REGISTRATIONS CLOSED for 2026-27 academic year. When open, extremely competitive — high demand, SPA assessment required. Over budget at ₹1.8L. For your timeline, admission probability is effectively zero unless waitlist opens.","bf":"Academic excellence seekers — but not viable for 2026-27 (admissions closed, over budget)","pros":["Highest CBSE scores in Bangalore","NPS brand is gold standard","56 SASMO medals","Strong infrastructure and systems"],"cons":["CLOSED for 2026-27 — not an option right now","Over ₹1.5L budget significantly","28:1 ratio","Rigid, pressure-heavy system","Not AI-age-optimal pedagogy"],"url":"https://www.npswhitefield.com","ph2":""},
{"n":"GIIS Whitefield","l":"Whitefield","z":"Whitefield","cor":"east","f":2.12,"fl":"~₹2.1L/yr (2026-27 est.)","b":"CBSE+Global","a":"Conceptual","r":"17:1","ri":17,"y":2010,"sz":"Medium","s":{"af":48,"co":80,"st":92,"ra":78,"op":80,"ac":72,"di":75,"inf":82,"al":55,"ad":72},"g":0,"ap":"Med-High","t":["AI/IoT/3D STEM studio","9 GEMS framework","Best STEM in corridor"],"tc":["g","p","g"],"ph":"Global Indian International School. Has a dedicated STEM studio with AI, IoT, and 3D technology — operational now, not planned. 9 GEMS holistic framework. Montessori-CBSE blend for early years. Part of global school network across multiple countries.","adm":"Global school with structured admission. Interaction-based assessment. Moderate competition. Over budget but the STEM infrastructure justification is real — no other school in the corridor has an operational AI/IoT/3D studio.","bf":"Families for whom STEM/AI infrastructure is the #1 priority — this school is unmatched in the corridor for tech readiness","pros":["Only operational AI/IoT/3D STEM studio in corridor","9 GEMS holistic framework","Global school network","Montessori early years","Strong digital infrastructure"],"cons":["Over ₹1.5L budget","Less optimized for Indian competitive exams","International focus may not suit all","Global curriculum can feel different from standard CBSE"],"url":"https://bangalore.globalindianschool.org","ph2":""},
{"n":"Deens Academy","l":"Whitefield ECC Road","z":"Whitefield","cor":"east","f":2.72,"fl":"~₹2.7L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"22:1","ri":22,"y":2006,"sz":"Large","s":{"af":29,"co":82,"st":75,"ra":70,"op":78,"ac":80,"di":75,"inf":78,"al":55,"ad":68},"g":0,"ap":"Med","t":["Empower & transform","MI theory","Parent School Alliance"],"tc":["g","p","b"],"ph":"'Not just to inform, but to empower and transform.' Theory of Multiple Intelligences for primary years. Deens Parent School Alliance (PSA) — formal parent voice in school policy. Multicultural environment. 3500+ students across 4 branches. ICT-enabled smartboards all classrooms. Kideens (their own preschool) has feeder priority.","adm":"Diagnostic assessment for Class 1+. First-come-first-served after assessment. ₹30K processing fee (non-refundable). Year-round admissions where vacancies exist. Important: Kideens preschool gets priority over external applicants — your Klay background means no advantage here.","bf":"Families with higher budget wanting proven empowerment-focused CBSE with strong parent involvement mechanisms","pros":["Empowerment philosophy — genuinely different","PSA gives parents real voice","Theory of Multiple Intelligences","Smartboards all classrooms","3500+ students = stability"],"cons":["Way over ₹1.5L budget at ₹2.25L","₹30K non-refundable processing fee","Kideens preschool gets priority — Klay doesn't","3.4 rating on YellowSlate (92 reviews) — mixed"],"url":"https://www.deensacademy.com","ph2":"admissions@deensacademy.com"},
{"n":"Holy Cross School","l":"Whitefield","z":"Whitefield","cor":"east","f":0.7,"fl":"~₹60-80K/yr (est.)","b":"CBSE","a":"Traditional","r":"20:1","ri":20,"y":2005,"sz":"Medium","s":{"af":93,"co":45,"st":35,"ra":75,"op":45,"ac":58,"di":78,"inf":48,"al":40,"ad":90},"g":0,"ap":"High","t":["Cheapest good option","Values-based","Save ₹70K+/yr"],"tc":["g","b","g"],"ph":"Balanced, holistic, integrated education with emphasis on instilling values. Opportunities for JEE/NEET competitive exam preparation. Very affordable — choosing this school frees up ₹70,000+ per year compared to a ₹1.5L school.","adm":"Standard admission. Not heavily competitive. Very accessible. High probability for any profile.","bf":"Budget-first families who want to redirect savings to emergency fund or supplement with external STEM/coding classes","pros":["Cheapest viable option in corridor","Frees ₹70K+/yr for savings/STEM classes","Values-based education","20:1 ratio — decent","JEE/NEET prep available"],"cons":["Traditional approach — more rote-oriented","Limited STEM infrastructure","Won't impress on innovation metrics","You'll need external coding/robotics supplementation"],"url":"","ph2":""},
{"n":"VIBGYOR High Marathahalli","l":"Marathahalli","z":"Marathahalli","cor":"east","f":1.98,"fl":"~₹1.98L/yr (2026-27 est.)","b":"ICSE/CISCE","a":"Mixed","r":"25:1","ri":25,"y":2004,"sz":"Large","s":{"af":53,"co":70,"st":72,"ra":62,"op":65,"ac":72,"di":72,"inf":75,"al":50,"ad":80},"g":0,"ap":"High","t":["ICSE","Since 2004","20yr track record"],"tc":["b","b","b"],"ph":"Established chain since 2004 with both academic and corporate professional founders. CISCE curriculum. Holistic development focus. 20-year track record in Marathahalli — one of the oldest established schools in the area.","adm":"Established chain — structured process, ample seats. ICSE admission interaction. High availability.","bf":"Families wanting an established 20-year ICSE school right in Marathahalli","pros":["20-year track record","ICSE board option","Right in Marathahalli","Ample seat availability","Corporate + academic founding team"],"cons":["Fees slightly over ₹1.5L","25:1 ratio — standard","Chain school — not exceptionally distinctive","Mixed reviews on innovation"],"url":"https://www.vibgyorhigh.com","ph2":""},
{"n":"Genius Global School","l":"Marathahalli","z":"Marathahalli","cor":"east","f":1.31,"fl":"~₹1.3L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"18:1","ri":18,"y":2012,"sz":"Small","s":{"af":76,"co":60,"st":55,"ra":78,"op":62,"ac":60,"di":65,"inf":58,"al":20,"ad":90},"g":1,"ap":"High","t":["Budget","18:1 ratio","Marathahalli"],"tc":["g","g","b"],"ph":"Dynamic learning environment with modern facilities. 18:1 student-teacher ratio is excellent for the price point. Located in Marathahalli. Inspires students to excel academically and personally.","adm":"Small school with available seats. Very accessible admission. Standard registration process.","bf":"Budget families in Marathahalli wanting surprisingly good ratio (18:1) at very low cost","pros":["18:1 ratio — exceptional for the price","Very affordable","Marathahalli location","Small school = more personal"],"cons":["Limited infrastructure","Small brand","Less proven track record","Limited STEM"],"url":"","ph2":""},
{"n":"BRS Global School","l":"Marathahalli-Whitefield Rd","z":"Marathahalli","cor":"east","f":1.15,"fl":"~₹1.1L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"30:1","ri":30,"y":2012,"sz":"Medium","s":{"af":81,"co":58,"st":48,"ra":52,"op":60,"ac":55,"di":65,"inf":50,"al":20,"ad":92},"g":1,"ap":"High","t":["Budget starter","Montessori KG","Marathahalli-Whitefield Rd"],"tc":["g","b","b"],"ph":"Montessori-KG blend for early learning years. CBSE affiliated. Co-educational day school. Envisions vibrant and holistic education. Located on the main Marathahalli-Whitefield road.","adm":"Very accessible. Always has seats. Standard registration. Easiest admission in the corridor.","bf":"Tightest-budget families who need to maximize savings — supplement STEM and coding externally","pros":["Very affordable","Montessori early years — good foundation","On main road — easy commute","Always has availability"],"cons":["30:1 ratio — large classes","Limited infrastructure","Limited STEM","Small brand — won't impress"],"url":"","ph2":""},
{"n":"BIA Whitefield","l":"Whitefield","z":"Whitefield","cor":"east","f":1.98,"fl":"~₹2.0L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"22:1","ri":22,"y":2010,"sz":"Medium","s":{"af":53,"co":68,"st":62,"ra":70,"op":72,"ac":65,"di":70,"inf":65,"al":35,"ad":82},"g":1,"ap":"High","t":["Multicultural","Times Ed award","Inclusive"],"tc":["b","p","g"],"ph":"Inclusive and multicultural environment. Won 'Most Improved School' and 'CED School Excellence' awards at EDU Excellence Summit. Times Education Excellence Award 2022. 60% of parents rate school positively. Known for accepting diverse backgrounds.","adm":"Growing school with standard admission. Usually has seats available. Not heavily oversubscribed.","bf":"Families valuing diversity, inclusion, and multicultural exposure above prestige or academic ranking","pros":["Genuinely multicultural","Multiple education awards","Inclusive by philosophy","Growing and improving","Standard admission — good availability"],"cons":["15% of parents flag infrastructure concerns","Not tier-1 in academic results","Still building brand","At upper edge of budget"],"url":"","ph2":""},
{"n":"Chrysalis High MARQ","l":"Whitefield/Varthur","z":"Whitefield","cor":"east","f":1.85,"fl":"~₹1.9L/yr (2026-27 est.)","b":"ICSE","a":"Conceptual","r":"11:1","ri":11,"y":2018,"sz":"Small","s":{"af":57,"co":85,"st":65,"ra":95,"op":82,"ac":68,"di":75,"inf":65,"al":30,"ad":78},"g":1,"ap":"Med-High","t":["11:1 ratio","ICSE option","Individual Support Program"],"tc":["g","b","g"],"ph":"ICSE branch of Chrysalis High. Same 11:1 ratio philosophy. Individual Support Program identifies key learning gaps and provides targeted intensity to bridge them. Chrysalis approach but with ICSE board.","adm":"Selective interaction process. Growing school with moderate competition. Good admission odds for strong profiles.","bf":"Families wanting the Chrysalis small-batch approach but prefer ICSE board over CBSE","pros":["11:1 ratio — same as Chrysalis CBSE","Individual Support Program — targeted gap-bridging","ICSE board — stronger in language","Conceptual approach"],"cons":["Newer than CBSE branch (est. 2018)","Smaller campus","Limited alumni","ICSE may limit some competitive exam prep"],"url":"https://chrysalishigh.com","ph2":""},
{"n":"Ryan Global School","l":"Kundalahalli/AECS Layout","z":"Kundalahalli","cor":"east","f":1.58,"fl":"~₹1.6L/yr (2026-27 est.)","b":"ICSE+Cambridge","a":"Mixed-Conceptual","r":"25:1","ri":25,"y":2010,"sz":"Medium","s":{"af":67,"co":68,"st":65,"ra":62,"op":65,"ac":70,"di":70,"inf":68,"al":55,"ad":82},"g":0,"ap":"High","t":["ICSE+Cambridge","Ryan Group","Kundalahalli"],"tc":["b","p","b"],"ph":"Ryan International Group. Offers both ICSE and Cambridge primary curriculum — dual board option. Located in Kundalahalli near AECS Layout and Brookefield. Part of one of India's largest school networks.","adm":"Part of Ryan Group — structured admission with ample capacity. High seat availability.","bf":"Families wanting ICSE + Cambridge dual option near Kundalahalli at affordable price","pros":["Dual board ICSE + Cambridge","Ryan Group reliability","Kundalahalli central location","Affordable","High availability"],"cons":["25:1 ratio","Chain model","Less distinctive pedagogy","Mixed approach — not purely conceptual"],"url":"","ph2":""},
{"n":"PNC Cognitio School","l":"Kadugodi","z":"Kadugodi","cor":"east","f":1.98,"fl":"~₹2.0L/yr (2026-27 est.)","b":"Cambridge","a":"Conceptual","r":"20:1","ri":20,"y":2010,"sz":"Medium","s":{"af":53,"co":82,"st":75,"ra":75,"op":82,"ac":72,"di":72,"inf":75,"al":35,"ad":72},"g":1,"ap":"Med-High","t":["Cambridge board","Kadugodi location","International curriculum"],"tc":["p","b","b"],"ph":"Cambridge Assessment International Education (CAIE) affiliated. Located in Kumbena Agrahara, Kadugodi. International curriculum at moderate Indian price point. Managed by Pillamma Nagamma Chinnappa Educational Trust.","adm":"Cambridge board schools attract specific profile — parents who've researched international curricula. Moderate competition. Consider board portability if you might move cities.","bf":"Families wanting genuine Cambridge international curriculum in Kadugodi at moderate cost","pros":["Cambridge board — internationally recognized","Kadugodi location accessible","Moderate price for international curriculum","Conceptual by design"],"cons":["Cambridge board — less common in India, may create transfer issues","Smaller school","At edge of ₹1.5L budget","Limited competitive exam alignment"],"url":"","ph2":""},
{"n":"Pratham International","l":"Varthur","z":"Varthur","cor":"east","f":1.58,"fl":"~₹1.6L/yr (2026-27 est.)","b":"ICSE","a":"Conceptual","r":"20:1","ri":20,"y":2010,"sz":"Medium","s":{"af":67,"co":72,"st":65,"ra":75,"op":70,"ac":68,"di":72,"inf":68,"al":30,"ad":82},"g":1,"ap":"High","t":["ICSE","Varthur","Holistic","Character building"],"tc":["b","b","g","g"],"ph":"ICSE school in Varthur. Holistic approach with emphasis on character building and co-curricular activities. Best in academics along with co-curricular activities and holistic approach since 2010.","adm":"Growing school in Varthur. Standard ICSE admission process. Good availability.","bf":"Families in Varthur wanting a holistic ICSE school with character-building emphasis","pros":["ICSE board","Varthur location — growing area","Holistic + character building","Affordable for ICSE","20:1 ratio — good"],"cons":["Smaller brand","Limited infrastructure compared to chains","Varthur still developing as area","Limited STEM investment"],"url":"","ph2":""},
{"n":"Insight Academy","l":"Marathahalli","z":"Marathahalli","cor":"east","f":1.39,"fl":"~₹1.4L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"25:1","ri":25,"y":2007,"sz":"Small","s":{"af":74,"co":60,"st":52,"ra":62,"op":60,"ac":58,"di":65,"inf":55,"al":20,"ad":90},"g":1,"ap":"High","t":["Budget","Marathahalli","Personal education"],"tc":["g","b","b"],"ph":"Focuses on fostering a personal education experience tailored to individual growth. Located on Thubarahalli, Whitefield Road behind Sriram Samriddhi Apartment. Small scale allows personalization.","adm":"Small school with available seats. Very accessible. Standard registration.","bf":"Budget families on Marathahalli-Whitefield road wanting personalized basics at low cost","pros":["Very affordable","Personal education approach","Marathahalli location","Small scale = more attention"],"cons":["Limited infrastructure","Only up to Class 10","Limited STEM","Small brand"],"url":"","ph2":""},
{"n":"Brilliant School","l":"Kundalahalli","z":"Kundalahalli","cor":"east","f":1.23,"fl":"~₹1.2L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"25:1","ri":25,"y":1991,"sz":"Medium","s":{"af":79,"co":58,"st":50,"ra":62,"op":58,"ac":60,"di":68,"inf":55,"al":25,"ad":90},"g":1,"ap":"High","t":["Since 1991!","33 years","Budget","Kundalahalli"],"tc":["p","p","g","b"],"ph":"Brilliant Group of Institutions established 1991 — 33 years in Kundalahalli. Mission to foster vibrant and humanized learning communities. One of the oldest private schools in the area.","adm":"Long-established school. Standard admission. Very accessible. Always has availability.","bf":"Budget families in Kundalahalli wanting a 33-year-old established institution at very low cost","pros":["33 years established — longest track record in Kundalahalli","Very affordable","Humanized learning community ethos","Known quantity — no surprises"],"cons":["Traditional approach","Limited modern infrastructure","Limited STEM investment","Not cutting-edge pedagogy"],"url":"","ph2":""},
{"n":"Carmel Teresa School","l":"Whitefield","z":"Whitefield","cor":"east","f":1.23,"fl":"~₹1.2L/yr (2026-27 est.)","b":"CBSE","a":"Traditional","r":"20:1","ri":20,"y":1887,"sz":"Small","s":{"af":79,"co":50,"st":40,"ra":75,"op":45,"ac":60,"di":80,"inf":55,"al":45,"ad":85},"g":0,"ap":"High","t":["Founded 1887!","139 years","Values","Budget"],"tc":["p","p","b","g"],"ph":"Established 1887 — one of the oldest schools in all of Whitefield. 139-year legacy. Spacious classrooms with wooden flooring and modern teaching aids. Indoor game facilities. Note: Classes only up to Class 8 — you'll need to transfer for high school.","adm":"Historic school with standard admission. Very accessible. High availability.","bf":"Families wanting historic, values-based affordable education (important note: only up to Class 8)","pros":["139-year legacy — oldest in Whitefield","Very affordable","Wooden flooring classrooms — unique charm","20:1 ratio","Strong values foundation"],"cons":["⚠ Only up to Class 8 — will need school transfer","Traditional pedagogy","Limited STEM","Small scale"],"url":"","ph2":""},
{"n":"Nava Prajna Public School","l":"Marathahalli-Airport-Whitefield Rd","z":"Marathahalli","cor":"east","f":1,"fl":"~₹1.0L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"22:1","ri":22,"y":2006,"sz":"Small","s":{"af":86,"co":55,"st":45,"ra":70,"op":58,"ac":55,"di":68,"inf":50,"al":20,"ad":92},"g":1,"ap":"High","t":["Absolute cheapest","IPS-founded","Student-centered"],"tc":["g","p","g"],"ph":"Founded by Late Dr. P.J. Bagilthaya, IPS (Retd) under Navajeevana Nilaya Trust. Student-centered approach to learning. Located on Airport-Whitefield Road near Marathahalli. Interactive boards in classrooms. Science and computer labs available.","adm":"Always has seats. Very accessible. Cheapest option in the entire corridor.","bf":"Absolute budget priority — every rupee saved goes to emergency fund or external enrichment","pros":["Cheapest in corridor — ₹50-80K","Founded by retired IPS officer — values-driven","Student-centered philosophy","Interactive boards available","22:1 ratio — decent for the price"],"cons":["Very limited infrastructure","Limited STEM investment","Small brand recognition","Only up to Class 10"],"url":"","ph2":""},
{"n":"Prajval Vidya Niketan","l":"Kaggadasapura/Malleshpalya","z":"Kaggadasapura","cor":"east","f":1.45,"fl":"~₹1.4L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"20:1","ri":20,"y":2014,"sz":"Small","s":{"af":72,"co":75,"st":62,"ra":75,"op":72,"ac":65,"di":72,"inf":62,"al":25,"ad":85},"g":1,"ap":"High","t":["Talk of parents","Kaggadasapura","Progressive","Affordable"],"tc":["g","b","g","g"],"ph":"Located in Malleshpalya/Kaggadasapura. Described as 'the talk of parents' by education reviewers. CBSE with progressive approach at affordable price. Growing reputation in the Kaggadasapura-Whitefield corridor.","adm":"Growing school with good availability. Standard admission. Not heavily oversubscribed.","bf":"Families in Kaggadasapura area wanting progressive CBSE at good value — a genuine hidden gem","pros":["Progressive approach at affordable price","Kaggadasapura location — underserved area","Parent buzz positive","20:1 ratio","Good value"],"cons":["Newer school — less track record","Limited infrastructure","Small brand","Limited alumni network"],"url":"","ph2":""},
{"n":"Harvest International","l":"Whitefield","z":"Whitefield","cor":"east","f":3.33,"fl":"~₹3.3L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"20:1","ri":20,"y":2010,"sz":"Large","s":{"af":18,"co":85,"st":82,"ra":75,"op":85,"ac":82,"di":80,"inf":90,"al":65,"ad":60},"g":0,"ap":"Med","t":["Premium holistic","India's Top CBSE","Best infrastructure"],"tc":["p","p","g"],"ph":"Awarded 'India's Top CBSE School'. Brainfeed Top 500 School Excellence Award. 65.33% of parents praise teaching quality. 29.33% highlight infrastructure excellence. 25.33% praise administration effectiveness. Premium pricing reflects premium everything.","adm":"Premium school = somewhat selective. Assessment + parent interview. Moderate competition at this price point. Way over your ₹1.5L budget — included for reference and for friends with higher budgets.","bf":"High-budget families wanting the best all-round infrastructure and holistic education in the corridor","pros":["India's Top CBSE School award","Best infrastructure in corridor","Strong teaching (65% parent praise)","Holistic development focus","20:1 ratio"],"cons":["Way over budget at ₹2.5-3L","Premium = selective admission","Nearly 2x your budget cap","May not justify 2x cost vs ₹1.5L schools"],"url":"","ph2":""},
{"n":"Headstart Montessori","l":"Whitefield","z":"Whitefield","cor":"east","f":2.42,"fl":"~₹2.4L/yr (2026-27 est.)","b":"Montessori→IGCSE","a":"Alternative","r":"15:1","ri":15,"y":2000,"sz":"Medium","s":{"af":39,"co":92,"st":65,"ra":80,"op":95,"ac":55,"di":68,"inf":72,"al":45,"ad":65},"g":0,"ap":"Med","t":["Pure Montessori K-18","Child-led","⚠ NOT CBSE"],"tc":["p","g","a"],"ph":"Genuine Montessori school from kindergarten through age 18, transitioning to IGCSE for board exams. Mixed-age groups. Child-led learning. 25+ year track record in Bangalore. This is NOT a CBSE school — fundamentally different educational philosophy.","adm":"Montessori philosophy requires parent alignment — they assess parent fit, not just child. Observation-based admission. Consider carefully: exiting CBSE means different board exam pathway. Over budget.","bf":"Families deeply committed to alternative education who are OK exiting the CBSE system entirely","pros":["Genuine Montessori — not just marketing","Child-led learning — most open system in corridor","25-year track record","15:1 ratio","IGCSE transition for board exams"],"cons":["NOT CBSE — board portability issues if you move cities","Over budget at ₹2L","Alternative approach may worry extended family","Less competitive exam alignment","Smaller peer group"],"url":"https://headstart.edu.in","ph2":""},
{"n":"Greenwood High","l":"Sarjapur Road","z":"Sarjapur","cor":"east","f":3.63,"fl":"~₹3.6L/yr (2026-27 est.)","b":"ICSE/IGCSE","a":"Conceptual","r":"20:1","ri":20,"y":2006,"sz":"Large","s":{"af":15,"co":82,"st":80,"ra":75,"op":80,"ac":85,"di":82,"inf":92,"al":75,"ad":55},"g":0,"ap":"Med","t":["#1 Intl School TOI","Premium legacy","₹3L+","ICSE not CBSE"],"tc":["p","p","r","b"],"ph":"Ranked #1 International School by Times of India. Creative freedom. Outstanding infrastructure — arguably the best campus in all of East/South Bangalore. ₹3L+ fees. ICSE and IGCSE curriculum, not CBSE.","adm":"Premium = selective admission. Assessment + parent interview. High demand from affluent families. Way over your budget. ICSE/IGCSE — not CBSE.","bf":"Highest-budget families wanting the #1 ranked school with best-in-class infrastructure (ICSE not CBSE)","pros":["#1 International School — Times of India","Best campus/infrastructure in broader area","Strong academic results","ICSE — stronger in language development","Creative freedom emphasized"],"cons":["Way over budget — 2x your cap at ₹3L","ICSE/IGCSE not CBSE","Sarjapur Road — check commute","Premium pricing may not justify 3x cost"],"url":"https://www.greenwoodhigh.edu.in","ph2":""},
{"n":"New Horizon Gurukul","l":"Kadubeesanahalli ORR","z":"Kadubeesanahalli","cor":"east","f":2.12,"fl":"~₹2.1L/yr (2026-27 est.)","b":"CBSE","a":"Traditional","r":"35:1","ri":35,"y":2005,"sz":"Very Large","s":{"af":48,"co":35,"st":60,"ra":30,"op":30,"ac":82,"di":65,"inf":72,"al":75,"ad":75},"g":0,"ap":"Med-High","t":["Exam factory","35:1 ratio","⚠ Rote-heavy","ORR location"],"tc":["a","r","r","b"],"ph":"Competitive exam focus. Very large batches (35:1). Result-oriented approach that drives strong board scores through pattern-based, rote learning. ORR location is convenient. New Horizon group has extensive alumni network.","adm":"Large school with ample seats. Standard admission. Not hard to get into. BUT — pedagogy is fundamentally rote-oriented, which contradicts AI-age education needs.","bf":"⚠ Families wanting pure competitive exam preparation — but NOT recommended for AI-age child development","pros":["Strong board results","ORR location — very convenient","New Horizon alumni network","Ample seat availability"],"cons":["⚠ 35:1 ratio — worst in corridor","⚠ Rote/pattern-based learning","⚠ Opposite of AI-age education needs","Over budget","Rigid system — little room for individual paths"],"url":"","ph2":""},
{"n":"Gopalan National School","l":"Whitefield","z":"Whitefield","cor":"east","f":1.72,"fl":"~₹1.7L/yr (2026-27 est.)","b":"ICSE","a":"Mixed","r":"22:1","ri":22,"y":2004,"sz":"Medium","s":{"af":61,"co":65,"st":62,"ra":70,"op":62,"ac":70,"di":72,"inf":72,"al":45,"ad":80},"g":0,"ap":"High","t":["Gopalan Group","ICSE","Whitefield","22yr track record"],"tc":["b","b","b","b"],"ph":"Gopalan Enterprises — long-standing reputation of sincerity and commitment across multiple fields including real estate and education. ICSE curriculum. 22-year track record in Whitefield.","adm":"Established group. Standard ICSE admission process. Good availability.","bf":"Families wanting an established ICSE option in Whitefield backed by a major Bangalore group","pros":["Gopalan Group — major institutional backing","ICSE board","22-year track record","Affordable for ICSE","Whitefield location"],"cons":["Not distinctive on pedagogy","Mixed approach — not strongly conceptual","Limited STEM innovation","Gopalan brand more known for real estate than education"],"url":"","ph2":""},
{"n":"Inventure Academy","l":"Whitefield/Sarjapur border","z":"Whitefield","cor":"east","f":3.75,"fl":"~₹3.8L/yr (2026-27 est.)","b":"Cambridge/ICSE","a":"Conceptual","r":"18:1","ri":18,"y":2005,"sz":"Medium","s":{"af":14,"co":90,"st":85,"ra":78,"op":88,"ac":88,"di":78,"inf":88,"al":70,"ad":45},"g":0,"ap":"Low-Med","t":["#1 Karnataka","54 world toppers","Fortune Future 50","Ultra premium"],"tc":["p","p","p","r"],"ph":"Ranked #1 in Karnataka & Bangalore, #3 in India by Education World. Fortune Future 50 Schools. 54 Cambridge World & Country toppers since 2010. 78% of students gain admission to top universities globally. Cambridge IGCSE, A/AS levels, and CISCE (ICSE/ISC).","adm":"Highly selective with entrance assessment. Very competitive — attracts top academic profiles. Way over budget. Premium positioning = limited seats.","bf":"Ultra-premium families wanting absolute best academic outcomes + global university placements","pros":["#1 in Karnataka — Education World","54 Cambridge world toppers","78% students → top universities","Fortune Future 50","18:1 ratio"],"cons":["Way over budget at ₹3.1L","Highly selective — hard to get in","Not CBSE","Sarjapur border — commute consideration","Ultra-premium may not justify 3x cost for primary school"],"url":"https://www.inventureacademy.com","ph2":""},
{"n":"The Brigade School","l":"Mahadevapura","z":"Mahadevapura","cor":"east","f":2.18,"fl":"~₹2.2L/yr (2026-27 est.)","b":"CBSE+ICSE","a":"Conceptual","r":"22:1","ri":22,"y":2005,"sz":"Large","s":{"af":46,"co":78,"st":75,"ra":70,"op":75,"ac":78,"di":78,"inf":82,"al":60,"ad":65},"g":0,"ap":"Med","t":["Brigade Group","Dual board","Mahadevapura"],"tc":["p","b","b"],"ph":"Brigade Group backing — one of Bangalore's most respected real estate and infrastructure groups. Mahadevapura campus offers both CBSE and ICSE options. Well-funded, established, with strong infrastructure.","adm":"Brigade brand = moderate-high demand. Assessment-based admission. Over budget. Mahadevapura campus — check proximity.","bf":"Families wanting corporate-backed school with dual board option near Mahadevapura tech corridor","pros":["Brigade Group — massive institutional backing","Dual board CBSE + ICSE","Well-funded campus","Strong infrastructure","Mahadevapura tech corridor location"],"cons":["Over ₹1.5L budget","Moderate admission competition","Brigade known for real estate, not education primarily","May not be closest to your area"],"url":"https://www.thebrigadeschool.in","ph2":""},
{"n":"Ravindra Bharathi","l":"Thubarahalli/Whitefield Rd","z":"Marathahalli","cor":"east","f":1.08,"fl":"~₹1.1L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"25:1","ri":25,"y":2008,"sz":"Small","s":{"af":83,"co":58,"st":48,"ra":62,"op":58,"ac":58,"di":68,"inf":52,"al":20,"ad":92},"g":1,"ap":"High","t":["Budget","Main road location","CBSE"],"tc":["g","b","b"],"ph":"CBSE affiliated school on Thubarahalli/Whitefield Road. Affordable option right on the main Marathahalli-Whitefield corridor.","adm":"Standard admission. Very accessible. High availability.","bf":"Budget families on the main Marathahalli-Whitefield road wanting CBSE basics at minimum cost","pros":["Very affordable","Main road location — easy access","CBSE board","High availability"],"cons":["Limited infrastructure","Limited STEM","Small brand","Basic facilities"],"url":"","ph2":""},
{"n":"TCIS Sarjapur","l":"Sarjapur Road","z":"Sarjapur Road","cor":"sarjapur","f":1.85,"fl":"~₹1.9L/yr (2026-27 est.)","b":"CBSE+IB","a":"Conceptual","r":"20:1","ri":20,"y":2015,"sz":"Medium","s":{"af":57,"co":92,"st":80,"ra":72,"op":90,"ac":78,"di":78,"inf":80,"al":55,"ad":78},"g":1,"ap":"High","t":["British Council","CBSE+IB","#2 Emerging TOI","SMART classrooms"],"tc":["p","b","g","b"],"ph":"Sister campus of TCIS Whitefield. CBSE+IB inquiry-based approach. Ranked #2 Emerging School Bangalore (TOI). British Council and Saint Felix global alliances. Trinity College London and Berklee music access. Child-centric differentiated learning.","adm":"Interaction-based admission. Progressive school with moderate competition. CBSE+IB blend attracts internationally-minded parents.","bf":"Progressive families on Sarjapur Road wanting international pedagogy at CBSE price","pros":["British Council + global alliances","CBSE+IB blend at moderate price","Trinity College London access","Inquiry-driven — minimal rote","#2 Emerging School TOI"],"cons":["Newer school — smaller alumni","20:1 ratio standard not exceptional","Fees at upper edge of ₹1.5L","Less competitive exam focus"],"url":"https://www.tcis.ac.in","ph2":"+91-80-42064444"},
{"n":"Cambridge Intl Sarjapur","l":"Haralur/Kudlu, off Sarjapur Rd","z":"Haralur","cor":"sarjapur","f":1.72,"fl":"~₹1.7L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"20:1","ri":20,"y":2012,"sz":"Medium","s":{"af":61,"co":82,"st":75,"ra":75,"op":78,"ac":75,"di":75,"inf":78,"al":45,"ad":80},"g":1,"ap":"High","t":["#1 Co-curricular India","Progressive inquiry","Sarjapur Road"],"tc":["p","g","b"],"ph":"Ranked #1 in Co-curricular Education in its category at India School Merit Awards 2022. Progressive inquiry-based education with traditional values. Best sports facilities, advanced labs, art/music spaces, smart classrooms.","adm":"Standard admission with interaction. Growing school with good availability. Located on 100ft Road, Haralur-Kudlu off Sarjapur Road.","bf":"Families wanting top co-curricular program + conceptual academics on Sarjapur corridor","pros":["#1 Co-curricular nationally","Strong sports infrastructure","Progressive inquiry-based","Within ₹1.5L budget","Good location on Sarjapur"],"cons":["CBSE only — no dual board","Still building academic reputation vs NPS/DPS","Moderate alumni network","20:1 ratio standard"],"url":"","ph2":""},
{"n":"MS Dhoni Global School","l":"HSR Layout","z":"HSR Layout","cor":"sarjapur","f":1.85,"fl":"~₹1.9L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"20:1","ri":20,"y":2018,"sz":"Medium","s":{"af":57,"co":78,"st":82,"ra":75,"op":75,"ac":70,"di":72,"inf":78,"al":50,"ad":78},"g":1,"ap":"Med-High","t":["Microsoft Showcase","STEM & robotics labs","Celebrity brand"],"tc":["p","g","b"],"ph":"First school in India to partner with Microsoft under Showcase School Incubator Program. CBSE with smart classrooms, STEM & robotics labs. Experiential learning through expos and field trips. Arts, music, dance, yoga, leadership programs.","adm":"Growing school with interaction-based admission. Microsoft partnership adds tech credibility. Moderate competition.","bf":"Tech-oriented families wanting Microsoft-backed STEM infrastructure in HSR Layout","pros":["Microsoft Showcase School — unique credential","STEM & robotics labs","Experiential learning emphasis","HSR Layout — prime location","Leadership programs"],"cons":["Celebrity branding — substance vs marketing question","Newer school (2018)","Fees at upper edge","Less proven board results track record"],"url":"","ph2":""},
{"n":"Primus Public School","l":"Sarjapur Road","z":"Sarjapur Road","cor":"sarjapur","f":1.98,"fl":"~₹2.0L/yr (2026-27 est.)","b":"ICSE/IGCSE","a":"Conceptual","r":"20:1","ri":20,"y":2010,"sz":"Medium","s":{"af":53,"co":80,"st":72,"ra":75,"op":75,"ac":75,"di":78,"inf":75,"al":45,"ad":75},"g":0,"ap":"Med-High","t":["ICSE+IGCSE+A-Level","Sans peur motto","Character development"],"tc":["b","p","g"],"ph":"'Sans peur' (Without fear) concept — encouraging brave and responsible people. ICSE, IGCSE, and A-Level programs. Complete education balancing academic rigor with character development. Strong holistic approach.","adm":"Interaction + assessment based. ICSE/IGCSE school attracts specific profile. Moderate competition.","bf":"Families wanting ICSE+international options with character-building focus on Sarjapur Road","pros":["Triple board option ICSE/IGCSE/A-Level","Character development emphasis","'Sans peur' philosophy builds confidence","Strong holistic approach","Sarjapur Road location"],"cons":["Fees slightly over ₹1.5L","ICSE may limit competitive exam prep","Moderate brand recognition","Not as established as Greenwood/Inventure"],"url":"","ph2":""},
{"n":"Orchids Sarjapur Road","l":"Sarjapur Road","z":"Sarjapur Road","cor":"sarjapur","f":1.65,"fl":"~₹1.6L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"15:1","ri":15,"y":2015,"sz":"Large","s":{"af":64,"co":72,"st":75,"ra":80,"op":65,"ac":72,"di":70,"inf":72,"al":45,"ad":88},"g":0,"ap":"High","t":["15:1 ratio","STEAM","75K+ alumni","Lush green campus"],"tc":["g","b","b","g"],"ph":"Part of Orchids chain — 110+ schools across India. 15:1 ratio. STEAM focus with digital classrooms. Sarjapur campus described as lush and green. STEM, arts, leadership, robotics, MUN, debates available. Free remedial classes.","adm":"Large chain — ample seats. Online application. Very accessible. High admission probability.","bf":"Families wanting reliable chain school with good ratio on Sarjapur Road","pros":["15:1 ratio","STEAM + robotics + MUN","Very high admission probability","Within budget","Green campus"],"cons":["Chain model — less unique","Quality varies by branch","Can feel standardized","Not deeply progressive"],"url":"https://www.orchidsinternationalschool.com/bangalore-branches/sarjapur-road","ph2":""},
{"n":"VIBGYOR High Haralur","l":"Haralur","z":"Haralur","cor":"sarjapur","f":1.98,"fl":"~₹2.0L/yr (2026-27 est.)","b":"CBSE+ICSE","a":"Conceptual","r":"10:1","ri":10,"y":2013,"sz":"Medium","s":{"af":53,"co":80,"st":75,"ra":98,"op":75,"ac":72,"di":78,"inf":80,"al":50,"ad":75},"g":1,"ap":"Med-High","t":["10:1 ratio!","Dual board","AC classrooms","Sports & performing arts"],"tc":["g","b","b","g"],"ph":"10:1 student-teacher ratio — best in Sarjapur corridor. Both CBSE and ICSE boards. AC classrooms, modern science labs. Strong emphasis on sports, performing arts, and supportive environment for all-round development. VIBGYOR group backing.","adm":"Growing campus. Interaction-based. Dual board offering widens appeal.","bf":"Families wanting the best ratio on Sarjapur corridor with dual board flexibility","pros":["10:1 ratio — exceptional","Dual board CBSE+ICSE","AC classrooms","Strong sports & performing arts","VIBGYOR group backing"],"cons":["Fees at upper edge of ₹1.5L","Currently up to Class 10 only","Haralur location — check distance","Newer campus"],"url":"","ph2":""},
{"n":"EuroSchool HSR","l":"HSR Layout","z":"HSR Layout","cor":"sarjapur","f":1.78,"fl":"~₹1.8L/yr (2026-27 est.)","b":"ICSE","a":"Conceptual","r":"19:1","ri":19,"y":2001,"sz":"Large","s":{"af":59,"co":78,"st":72,"ra":78,"op":70,"ac":72,"di":75,"inf":78,"al":50,"ad":80},"g":0,"ap":"High","t":["ICSE board","25yr legacy","LRPAX method","HSR prime location"],"tc":["b","p","b","g"],"ph":"EuroSchool HSR — one of the oldest EuroSchool campuses (est. 2001). ICSE board. LRPAX methodology. Well-designed spacious environment. Modern labs, reading rooms, computer labs, sports coaches, smart-class technology. Serves HSR Layout, Sarjapur Road, Koramangala families.","adm":"Established campus — structured admission with good availability. ICSE board. Chain reliability.","bf":"Families wanting reliable ICSE chain school in prime HSR Layout location","pros":["25-year track record at HSR","ICSE board","LRPAX method — anti-rote","19:1 ratio","Prime HSR location"],"cons":["ICSE only — no CBSE option","Chain school feel","Not cutting-edge on STEM","Moderate innovation"],"url":"","ph2":""},
{"n":"Bethany High Sarjapur","l":"Sarjapur Road","z":"Sarjapur Road","cor":"sarjapur","f":1.85,"fl":"~₹1.9L/yr (2026-27 est.)","b":"ICSE","a":"Conceptual","r":"20:1","ri":20,"y":2013,"sz":"Medium","s":{"af":57,"co":78,"st":68,"ra":75,"op":72,"ac":72,"di":78,"inf":72,"al":40,"ad":78},"g":0,"ap":"Med-High","t":["ICSE","Values-based","Best ICSE 2024 nearby"],"tc":["b","g","g"],"ph":"ICSE-affiliated school on Sarjapur Road. Values-based education with focus on academics and character. Part of the broader Bethany schools network in Bangalore.","adm":"Standard ICSE admission with interaction. Moderate competition.","bf":"Families wanting values-based ICSE education on Sarjapur Road","pros":["ICSE board — stronger in language","Values-based approach","Decent ratio","Within budget range","Sarjapur location"],"cons":["Less known than Greenwood/Inventure","Limited STEM standout","Moderate infrastructure","Smaller alumni base"],"url":"","ph2":""},
{"n":"Amaatra Academy","l":"Haralur, off Sarjapur Road","z":"Haralur","cor":"sarjapur","f":1.72,"fl":"~₹1.7L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"18:1","ri":18,"y":2019,"sz":"Small","s":{"af":61,"co":82,"st":68,"ra":78,"op":80,"ac":65,"di":72,"inf":70,"al":20,"ad":82},"g":1,"ap":"High","t":["Nurturing approach","18:1 ratio","Day+residential","Amphitheatre"],"tc":["g","g","b","b"],"ph":"CBSE-affiliated school offering both day and residential programs. Motto: nurture a child steadily and sensitively while keeping eye on absorbent mind and developmental needs. Smart classrooms, science labs, sports, amphitheatre, digital library. Wide co-curricular and leadership activities.","adm":"Newer school (2019) — usually has good availability. Interaction-based. Both day and residential options unusual at this price.","bf":"Families wanting nurturing, sensitive approach with boarding option on Sarjapur corridor","pros":["18:1 ratio — very good","Both day and residential options","Amphitheatre and digital library","Nurturing philosophy","Within budget"],"cons":["Very new (2019) — limited track record","Small school — limited alumni","Still establishing reputation","Less proven board results"],"url":"","ph2":""},
{"n":"Freedom Intl School","l":"HSR Layout","z":"HSR Layout","cor":"sarjapur","f":1.94,"fl":"~₹1.9L/yr (2026-27 est.)","b":"CBSE","a":"Alternative","r":"15:1","ri":15,"y":2012,"sz":"Small","s":{"af":54,"co":90,"st":65,"ra":80,"op":92,"ac":62,"di":70,"inf":65,"al":30,"ad":72},"g":1,"ap":"Med-High","t":["Interactive classrooms","Nature-integrated","Progressive alt"],"tc":["g","g","g"],"ph":"Classrooms are lively, lessons interactive — sometimes interrupted by a teacher who discovered an unusual insect or plant in the garden. Nature-integrated learning. Progressive alternative approach within CBSE framework. Small, intentional school community.","adm":"Small school — limited seats. Philosophy-alignment important for admission. Over ₹1.5L budget.","bf":"Families wanting genuinely alternative, nature-integrated education within CBSE structure in HSR","pros":["Nature-integrated — rare in Bangalore","15:1 ratio","Genuinely progressive","Interactive lively classrooms","Small intentional community"],"cons":["Over ₹1.5L budget","Very small — limited seats","Limited infrastructure","Less academic rigor focus","Tiny alumni network"],"url":"","ph2":""},
{"n":"Ryan Intl Academy Sarjapur","l":"Sarjapur Road","z":"Sarjapur Road","cor":"sarjapur","f":1.98,"fl":"~₹2.0L/yr (2026-27 est.)","b":"CBSE+ICSE+IGCSE+IB","a":"Conceptual","r":"22:1","ri":22,"y":2015,"sz":"Large","s":{"af":53,"co":75,"st":75,"ra":70,"op":70,"ac":75,"di":75,"inf":80,"al":60,"ad":78},"g":0,"ap":"Med-High","t":["4 boards!","Best sports infra","Ryan Group","21st century skills"],"tc":["p","g","p","b"],"ph":"Part of Ryan International Group. Unique offering of FOUR boards: CBSE, ICSE, IGCSE, and IB. Best-in-class sports infrastructure. 21st-century skills curriculum. Well-rounded approach.","adm":"Ryan Group — structured admission. Multiple board options mean diverse applicant pool.","bf":"Families wanting maximum board flexibility + strong sports on Sarjapur Road","pros":["4 board options — unmatched flexibility","Strong sports infrastructure","Ryan Group reliability","21st century skills focus","Well-resourced campus"],"cons":["Fees at ₹1.5L+ range","22:1 ratio — standard","Chain model","Jack of all boards, master of none risk"],"url":"","ph2":""},
{"n":"Orchids Haralur","l":"Haralur","z":"Haralur","cor":"sarjapur","f":1.65,"fl":"~₹1.6L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"25:1","ri":25,"y":2016,"sz":"Large","s":{"af":64,"co":70,"st":72,"ra":62,"op":65,"ac":70,"di":70,"inf":70,"al":45,"ad":88},"g":0,"ap":"High","t":["CBSE","Chain reliable","Haralur location"],"tc":["b","b","b"],"ph":"Orchids chain campus in Haralur. CBSE affiliated. Standard Orchids curriculum with STEAM focus, digital classrooms, and co-curricular activities. Serves Haralur, Sarjapur, HSR families.","adm":"Large chain — very accessible. High admission probability. Standard online application.","bf":"Budget-conscious families in Haralur wanting reliable chain school basics","pros":["Within budget","High admission probability","Chain reliability","Haralur location","STEAM basics"],"cons":["25:1 ratio — larger than Sarjapur branch","Chain standardization","Less distinctive","Not standout on any parameter"],"url":"","ph2":""},
{"n":"Patel Public School","l":"Bellandur","z":"Bellandur","cor":"sarjapur","f":1.45,"fl":"~₹1.4L/yr (2026-27 est.)","b":"ICSE","a":"Mixed","r":"15:1","ri":15,"y":2006,"sz":"Medium","s":{"af":72,"co":65,"st":58,"ra":80,"op":62,"ac":68,"di":72,"inf":65,"al":35,"ad":85},"g":1,"ap":"High","t":["15:1 ratio","ICSE","Bellandur","Affordable"],"tc":["g","b","b","g"],"ph":"Co-educational ICSE school est. 2006 by Patel Group. Located in Bellandur near ORR — ideal for ITPL, Marathahalli, HAL, Whitefield families too. 15:1 ratio. Focused on developing future leaders through strong academic foundation.","adm":"Standard ICSE admission. Good availability. Accessible location near ORR.","bf":"Families in Bellandur wanting affordable ICSE with excellent 15:1 ratio","pros":["15:1 ratio at affordable price","ICSE board","Bellandur ORR location — central","20 years established","Good value"],"cons":["Mixed approach — not strongly conceptual","Basic infrastructure","State board option too (dilutes focus)","Limited STEM innovation"],"url":"","ph2":""},
{"n":"Narayana e-Techno Bellandur","l":"Bellandur","z":"Bellandur","cor":"sarjapur","f":1.58,"fl":"~₹1.6L/yr (2026-27 est.)","b":"CBSE","a":"Traditional","r":"30:1","ri":30,"y":2015,"sz":"Large","s":{"af":67,"co":40,"st":60,"ra":45,"op":35,"ac":80,"di":65,"inf":65,"al":60,"ad":82},"g":0,"ap":"High","t":["Exam-focused","Narayana brand","⚠ Rote-heavy","Bellandur"],"tc":["a","p","r","b"],"ph":"Part of Narayana Group — integrated CBSE syllabus with micro-schedule defining preparation hour-by-hour. Strong competitive exam focus. Added advantage for JEE/NEET preparation from early years.","adm":"Large chain — ample seats. Standard admission. High availability.","bf":"⚠ Families wanting pure competitive exam prep — NOT recommended for AI-age readiness","pros":["Narayana brand — strong exam results","Affordable","Bellandur location","High availability","JEE/NEET integrated prep"],"cons":["⚠ 30:1 ratio","⚠ Hour-by-hour micro-schedule = extreme rote","⚠ Opposite of AI-age education","Rigid system","Little room for creativity"],"url":"","ph2":""},
{"n":"Endeavour's Academy","l":"Sarjapur Road","z":"Sarjapur Road","cor":"sarjapur","f":1.58,"fl":"~₹1.6L/yr (2026-27 est.)","b":"CBSE","a":"Conceptual","r":"20:1","ri":20,"y":2018,"sz":"Small","s":{"af":67,"co":82,"st":62,"ra":75,"op":82,"ac":62,"di":70,"inf":65,"al":20,"ad":85},"g":1,"ap":"High","t":["Arts-focused","Imaginative thinking","Affordable progressive"],"tc":["g","g","g"],"ph":"Promotes imaginative thinking through immersive experiences in art, theatre, music, and literature. CBSE-affiliated with spacious campus, digital classrooms, labs, and multipurpose hall. Focus on creativity alongside academics.","adm":"Newer school (2018) — usually has availability. Standard admission. Affordable.","bf":"Families wanting arts-integrated progressive education at budget price on Sarjapur Road","pros":["Arts + imagination focus — rare","Affordable for progressive school","Within budget","Creative thinking emphasis","Good availability"],"cons":["Very new (2018)","Small school","Limited track record","Limited STEM standout","Tiny alumni"],"url":"","ph2":""},
{"n":"NPS Silk Board","l":"Begur Village, off Hosur Rd","z":"Silk Board","cor":"sarjapur","f":1.94,"fl":"~₹1.9L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"25:1","ri":25,"y":2021,"sz":"Medium","s":{"af":54,"co":68,"st":78,"ra":62,"op":50,"ac":80,"di":80,"inf":82,"al":80,"ad":72},"g":0,"ap":"Med-High","t":["NPS Super 4","NPS brand","New campus"],"tc":["p","p","g"],"ph":"Part of NPS Super 4 (Whitefield, East, Marathahalli, Silk Board). Same management and pedagogy. Lexile Framework. Interactive panels. NPS Connect parent portal. 3-acre campus in Begur.","adm":"NPS brand = competitive. Still newer campus so slightly more availability than NPS Whitefield. SPA assessment required.","bf":"Families wanting NPS quality near Silk Board junction / south Sarjapur corridor","pros":["NPS brand and pedagogy","Part of Super 4 network","Strong infrastructure","Accepting admissions","Proven NPS system"],"cons":["Over ₹1.5L budget","NPS can be rigid/pressure-heavy","25:1 ratio","Silk Board location — check commute from HSR/Sarjapur","Newer campus culture developing"],"url":"https://npssilkboard.com","ph2":""},
{"n":"Greenwood High","l":"Sarjapur Road","z":"Sarjapur Road","cor":"sarjapur","f":3.63,"fl":"~₹3.6L/yr (2026-27 est.)","b":"ICSE/IGCSE","a":"Conceptual","r":"20:1","ri":20,"y":2006,"sz":"Large","s":{"af":15,"co":82,"st":80,"ra":75,"op":80,"ac":85,"di":82,"inf":92,"al":75,"ad":55},"g":0,"ap":"Med","t":["#1 Intl School TOI","Premium","₹3L+"],"tc":["p","p","r"],"ph":"Ranked #1 International School by Times of India. Creative freedom. Outstanding infrastructure — arguably best campus in South-East Bangalore. ₹3L+ fees. ICSE and IGCSE.","adm":"Premium = selective. Assessment + parent interview. High demand. Way over most budgets.","bf":"Ultra-premium families wanting #1 ranked school with best infrastructure","pros":["#1 International School TOI","Best infrastructure","Strong academics","Creative freedom"],"cons":["Way over budget at ₹3L","Selective admission","ICSE not CBSE","Premium pricing"],"url":"https://www.greenwoodhigh.edu.in","ph2":""},
{"n":"Inventure Academy","l":"Sarjapur-Whitefield border","z":"Sarjapur Road","cor":"sarjapur","f":3.75,"fl":"~₹3.8L/yr (2026-27 est.)","b":"Cambridge/ICSE","a":"Conceptual","r":"18:1","ri":18,"y":2005,"sz":"Medium","s":{"af":14,"co":90,"st":85,"ra":78,"op":88,"ac":88,"di":78,"inf":88,"al":70,"ad":45},"g":0,"ap":"Low-Med","t":["#1 Karnataka","54 world toppers","Fortune Future 50"],"tc":["p","p","p"],"ph":"#1 in Karnataka & Bangalore, #3 India (Education World). Fortune Future 50 Schools. 54 Cambridge World & Country toppers. 78% students → top universities globally.","adm":"Highly selective. Entrance assessment. Very competitive. Way over budget.","bf":"Ultra-premium families wanting absolute best academic outcomes + global placements","pros":["#1 Karnataka","54 world toppers","78% → top universities","18:1 ratio"],"cons":["₹3.1L — way over budget","Highly selective","Not CBSE","Ultra-premium"],"url":"https://www.inventureacademy.com","ph2":""},
{"n":"Chevalier Academy","l":"Sarjapur area","z":"Sarjapur Road","cor":"sarjapur","f":1.58,"fl":"~₹1.6L/yr (2026-27 est.)","b":"CBSE","a":"Mixed-Conceptual","r":"22:1","ri":22,"y":2012,"sz":"Small","s":{"af":67,"co":72,"st":58,"ra":70,"op":72,"ac":65,"di":80,"inf":60,"al":25,"ad":85},"g":1,"ap":"High","t":["LIVE LEARN LOVE","Values-driven","Affordable"],"tc":["g","g","g"],"ph":"Committed to nurturing young minds to LIVE fully, LEARN lifelong, and LOVE God, Country, Community. Values-driven education building strength, capability and resilience. Cultural values + 21st century skills blend.","adm":"Smaller school — usually has availability. Values-alignment important. Accessible.","bf":"Values-driven families wanting affordable character-building education on Sarjapur corridor","pros":["Strong values framework","Affordable","Within budget","Character building emphasis","Smaller community feel"],"cons":["Limited infrastructure","Less known brand","Limited STEM","Smaller scale","Less academic prestige"],"url":"","ph2":""},
{"n":"Lawrence High School","l":"HSR Layout","z":"HSR Layout","cor":"sarjapur","f":1.32,"fl":"~₹1.3L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"28:1","ri":28,"y":2005,"sz":"Large","s":{"af":76,"co":62,"st":55,"ra":55,"op":60,"ac":68,"di":72,"inf":65,"al":40,"ad":85},"g":0,"ap":"High","t":["Affordable","HSR Layout","Established"],"tc":["g","b","b"],"ph":"Established school in HSR Layout. CBSE curriculum. Standard approach with decent track record. Affordable option in an expensive area.","adm":"Standard admission. Good availability. HSR Layout location convenient.","bf":"Budget-conscious families in HSR wanting established basics at low cost","pros":["Very affordable for HSR location","Established since 2005","HSR prime location","High availability","Decent track record"],"cons":["28:1 ratio — larger classes","Not innovative on pedagogy","Limited STEM","Traditional approach"],"url":"","ph2":""},
{"n":"Gnan Srishti School","l":"HSR Layout","z":"HSR Layout","cor":"sarjapur","f":1.45,"fl":"~₹1.4L/yr (2026-27 est.)","b":"CBSE","a":"Mixed-Conceptual","r":"22:1","ri":22,"y":2010,"sz":"Small","s":{"af":72,"co":70,"st":60,"ra":70,"op":70,"ac":65,"di":72,"inf":62,"al":25,"ad":85},"g":1,"ap":"High","t":["Affordable","HSR Layout","Progressive basics"],"tc":["g","b","g"],"ph":"School of excellence in HSR Layout. CBSE with focus on holistic development. Smaller school providing more personalized attention. Progressive basics at affordable price.","adm":"Standard admission. Good availability. Smaller school — more personal process.","bf":"Families in HSR wanting affordable school with some progressive approach at budget price","pros":["Affordable","HSR location","22:1 ratio decent","Some progressive approach","Good availability"],"cons":["Small school","Limited infrastructure","Limited STEM","Less brand recognition","Small alumni"],"url":"","ph2":""},
{"n":"Indus International","l":"Sarjapur Road","z":"Sarjapur Road","cor":"sarjapur","f":6.05,"fl":"~₹6.0L/yr (2026-27 est.)","b":"IB (PYP/MYP/DP)","a":"Conceptual","r":"15:1","ri":15,"y":2003,"sz":"Large","s":{"af":10,"co":92,"st":85,"ra":80,"op":90,"ac":85,"di":82,"inf":95,"al":70,"ad":40},"g":0,"ap":"Low-Med","t":["#1 IB School 13yrs","40-acre campus","33 nationalities","Ultra premium"],"tc":["p","g","p","r"],"ph":"Ranked India's #1 international day-cum-boarding school for 13 consecutive years (C-Fore 2012-2024). Full IB continuum: PYP, MYP, DP. 40-acre campus. 1,100+ students from 33 countries. Ecosystem rooted in love, respect, empathy, discipline.","adm":"Highly selective. IB school = specific philosophy alignment required. Way over budget.","bf":"Ultra-premium families wanting full IB continuum with global student body on 40-acre campus","pros":["#1 IB school 13 consecutive years","40-acre campus — largest","33 nationalities","Full IB PYP/MYP/DP","World-class infrastructure"],"cons":["₹5L+ — way over most budgets","IB only — no CBSE/ICSE","Highly selective","Ultra-premium","Different assessment system from mainstream"],"url":"https://www.indusschool.com","ph2":""},
{"n":"BRS Global Kasavanahalli","l":"Kasavanahalli, Sarjapur Main Rd","z":"Kasavanahalli","cor":"sarjapur","f":1.15,"fl":"~₹1.1L/yr (2026-27 est.)","b":"CBSE","a":"Mixed","r":"28:1","ri":28,"y":2012,"sz":"Medium","s":{"af":81,"co":58,"st":48,"ra":55,"op":60,"ac":55,"di":65,"inf":50,"al":20,"ad":92},"g":1,"ap":"High","t":["Budget","Montessori KG","Kasavanahalli"],"tc":["g","b","b"],"ph":"CBSE affiliated. Blend of KG and Montessori curriculum for early learning. Dedicated to academic knowledge and responsible citizenship. Attention to individual students.","adm":"Very accessible. Always has availability. Standard registration.","bf":"Tightest-budget families on Sarjapur corridor — supplement STEM externally","pros":["Very affordable","Montessori early years","Always available","Kasavanahalli accessible","Individual attention claimed"],"cons":["28:1 ratio","Limited infrastructure","Limited STEM","Basic facilities","Small brand"],"url":"","ph2":""}
];

const CRITERIA = [
  {
    "id": "af",
    "n": "Affordability",
    "w": 18,
    "d": "Lower fees = higher score. At ₹35L household income with AI career disruption risk, every lakh matters."
  },
  {
    "id": "co",
    "n": "Conceptual learning",
    "w": 16,
    "d": "Understanding-based, not rote memorization. Critical for AI-age readiness — pattern-matching jobs are exactly what AI replaces."
  },
  {
    "id": "st",
    "n": "STEM & AI ready",
    "w": 14,
    "d": "Labs, robotics, digital infrastructure, AI curriculum preparedness. CBSE mandates AI from Class 3 in 2026-27."
  },
  {
    "id": "ra",
    "n": "Student-teacher ratio",
    "w": 12,
    "d": "Smaller classes = more individual attention. Research consistently shows this is the #1 factor in primary school outcomes."
  },
  {
    "id": "op",
    "n": "Open system",
    "w": 10,
    "d": "Flexible, responsive to feedback, not rigid. Schools with parent voice mechanisms adapt better."
  },
  {
    "id": "ac",
    "n": "Academic results",
    "w": 8,
    "d": "Board scores, competitive exam foundation, university placement track record."
  },
  {
    "id": "di",
    "n": "Discipline & values",
    "w": 7,
    "d": "Balanced discipline (not authoritarian), safety, anti-bullying, values education."
  },
  {
    "id": "inf",
    "n": "Infrastructure",
    "w": 6,
    "d": "Campus quality, sports facilities, labs, library, transport, technology."
  },
  {
    "id": "al",
    "n": "Alumni & brand",
    "w": 5,
    "d": "Network strength, brand recognition, legacy, institutional stability."
  },
  {
    "id": "ad",
    "n": "Admission probability",
    "w": 4,
    "d": "Your specific chance of getting in — based on school size, demand, selection process, and your Klay/no-priority profile."
  }
];
